<?php

    /**
     * Created by PhpStorm.
     * User: rom
     * Date: 6/14/17
     * Time: 12:01 PM
     */

    namespace App\Controller;

    use Cake\Event\Event;

    class BuyersController extends AppController
    {

        public function beforeFilter(Event $event)
        {
            parent::beforeFilter($event); // TODO: Change the autogenerated stub

            $this->Auth->allow(['add','home']);
        }

        public function add()
        {

            $buyer = $this->Buyers->newEntity();

            if ($this->request->is('post')) {

                $data = $this->request->getData();

                $data['user']['role_id'] = 3;

                $buyer = $this->Buyers->patchEntity($buyer, $data,['associated' => ['Users']]);

                if ($this->Buyers->save($buyer)) {

                    $this->Flash->success(__('Buyer has been saved'));
                    return $this->redirect(['controller' => 'Users', 'action' => 'login']);
                }
            }

            $qualifications = $this->Buyers->Qualifications->getList();
            $incomes = $this->Buyers->Incomes->getList();
            $jobs = $this->Buyers->Jobs->getList();
            $gender = array(0 => 'Not known', 1 => 'Male', 2 => 'Female', 9 => 'Not Applicable');
            $this->set(compact('buyer', 'qualifications', 'incomes', 'jobs', 'gender'));
            $this->set('_serialize', ['buyer', 'qualifications', 'incomes', 'jobs', 'gender']);

        }

        public function home()
        {
            $this->loadModel('Users');
            $this->loadModel('Polls');

            $user = $this->Auth->user();
            $buyer = $this->Users->getBuyerId($user['id']);

            $poll = $this->Polls->isOpen($buyer);

            if( $poll === null )
                $poll = $this->Polls->init($buyer);

            $this->set(compact('user','buyer', 'poll'));
            $this->set('_serialize',['user','buyer', 'poll']);
        }

    }