<?php
    /**
     * Created by PhpStorm.
     * User: rom
     * Date: 6/22/17
     * Time: 7:40 PM
     */

    namespace App\Controller;


    use Cake\Event\Event;

    class MapsController extends AppController
    {

        public function beforeFilter(Event $event)
        {
            parent::beforeFilter($event); // TODO: Change the autogenerated stub
            $this->Auth->allow(['getSubSectionsGeoJSON','getParishesZonesGeoJSON']);
        }

        public function getParishesZonesGeoJSON()
        {
            $this->loadModel('Zones');
            $this->loadModel('Regions');

            $params = $this->request->getQueryParams();
            $id = $params['id'];
            $response = '';
            if ($this->request->is('ajax')) {

                $response = 'ahahah';
                // get camera center coordintes
                $camera = json_decode($this->Regions->getCentroid($id));

                // get  zones geoJson info  that belongs to $id
                $geoJSON = $this->Regions->toFeatureCollection($this->Zones->getParishesZonesGeoJSON($id));
            }
            $this->set(compact('camera', 'geoJSON','response'));
            $this->set('_serialize', ['camera', 'geoJSON','response']);
        }






    }