<?php
    /**
     * Created by PhpStorm.
     * User: rom
     * Date: 6/14/17
     * Time: 12:00 PM
     */

    namespace App\Controller;


    use Cake\Event\Event;

    class SellersController extends AppController
    {

        public function beforeFilter(Event $event)
        {
            parent::beforeFilter($event); // TODO: Change the autogenerated stub
            $this->Auth->allow(['add','home']);
        }

        public function add()
        {



            $seller = $this->Sellers->newEntity();

            if ($this->request->is('post')) {
                $data = $this->request->getData();

                $data['user']['role_id'] = 2;
                $seller = $this->Sellers->patchEntity($seller, $data, ['associated' => ['Users','Addresses']]);


                if ($this->Sellers->save($seller)) {
                    $this->Flash->success(__('Seller has been saved'));
                    return $this->redirect(['controller' => 'Users', 'action' => 'login']);
                }

            }

            $seller_types = $this->Sellers->SellerTypes->getTypesList();
            $addresses = $this->Sellers->Addresses->find('all');



            $this->set(compact('seller', 'seller_types'));
            $this->set('_serialize', ['seller', 'seller_types']);


        }

        public function home()
        {
        }

    }